### ISSUE TITLE
Add option to output to STDOUT

### ISSUE THREAD

**Issue by evert** [coreyarms/mysql-types-generator#13]
It would be nice if we could also just have the tool emit its output to stdout, making it potentially easier to compose it with other unix tools.

One way to implement this is to do this by default if neither `--outDir` nor `--outFile` is specified. In the Javascript API we probably want a third option after `file` and `dir`, perhaps `stream` ? 

(low priority for me)

**Comment by coreyarms** [comment]
Sure, that makes sense for the CLI options. For the JS API, you mean `{ stream: fs.WriteStream; }` ? 

 Personally I have no use for this feature right now but I don't see any harm in adding it.

**Comment by evert** [comment]
Yeah, mainly thinking about this for the CLI case, and indeed that type looks good.
