### ISSUE TITLE
The NodeJS version checker in the CLI is wrong

### ISSUE THREAD

**Issue by joakimbeng** [coreyarms/mysql-types-generator#18]
The current check transforms NodeJS v18.3 to the number `18.3` and transforms v18.11 to `18.11`.
This means that `18.3 > 18.11` which is not correct according to semver.
You have to make the minor a two digit number by zero padding it if it's only one digit.
So v18.3 would become the number `18.03`...

**Comment by evert** [comment]
Created a PR for this in #19
