### ISSUE TITLE
Use with npx

### ISSUE THREAD

**Issue by evert** [coreyarms/mysql-types-generator#2]
I like command line tools. Would you accept a patch that adds a `bin/mysql-mysql-types-generator` that lets me specify all the configuration on the command line?

**Comment by coreyarms** [comment]
Yes definitely. To be honest a CLI tool is probably a better approach for this project. If you implement it I would ensure to keep it updated as I add features in the future. Or if you give me a starter template I can implement it, I've just never built a CLI tool before.
