### ISSUE TITLE
'decimal' should probably map to string

### ISSUE THREAD

**Issue by evert** [coreyarms/mysql-types-generator#22]
I think it would probably be a good idea for this library to default to what the mysql2 library does in terms of automatically mapping types.

The one I'm running into is `decimal` this is normally used for things like money, where you explicitly don't want funny float-like rounding (unlike `DOUBLE` or `FLOAT`). mysql2 will map this to a `string`.

**Comment by coreyarms** [comment]
Yeah that makes sense. I think to change the default it would probably need to be version 2.0.0 since it would break a couple of apps I have in production. What do you think?

**Comment by evert** [comment]
I missed the reply to this, but agreed... might as well cut a new major version for this (although I think you could consider this a bug, no MySQL client that I'm aware of will emit this as a `number`).

I just ran into this again, getting ints instead of strings. Luckily there's the column override feature ;)
