### ISSUE TITLE
Plz release!

### ISSUE THREAD

**Issue by evert** [coreyarms/mysql-types-generator#25]
Hey @coreyarms ,

mysql-types-generator has been blocking me from upgrading mysql2, which fixed a critical security issue. As a result I've had a few projects stating "critical security vulnerability". This is fixed in v2 but it's currently unreleased.

Any chance we can get a v2 release (or a v1 release with an updated mysql2 dependency?)

**Comment by coreyarms** [comment]
Released and published 2.0.0

**Comment by evert** [comment]
thank you!!
