### ISSUE TITLE
Ability to put everything in a single file

### ISSUE THREAD

**Issue by evert** [coreyarms/mysql-types-generator#3]
I would like to combine the result of this tool into a single file and possibly also add  a comment at the top such as:

```javascript
/**
 * This file is auto-generated. Don't manually edit this bla bla
 */


export type TableA {

}

etc
```

Is that a feature you'd be potentially interested in?

I woke up today thinking I wanted to write a tool like this, and saw you released today. I'm definitely up for contributing my requests but wanted to gauge interest before sending PRs.

**Comment by coreyarms** [comment]
Yes that's a good idea. In my case my databases have too many tables to be in 1 file so I just assumed they should be in separate files. Even in that case I like the idea of putting that comment at the top of each file, I will definitely do that.

Maybe it could check the `config.output.path` and if it's a directory it generates separate files, and if it's a file it generates 1 file?  Or I could just add another property to `config.output`.

Thanks for your ideas by the way!

**Comment by coreyarms** [comment]
Fixed in `0.0.11`:
- if `output.path` is a file (ending in `.ts`), all types will be output into that single file. If `output.path` is a directory, each type will have its own file and an `index.ts` will also be generated
- Each output file now has a warning comment message at the top

**Comment by evert** [comment]
I feel the 'unix way' to do something like this might be to check if the path ends in a slash. If yes, it's a directory. Another example, typescript's `tsc` command simply has 2 separate flags (outDir and outFile).

Depending on `.ts` at the end feels a little magic to me, but I can take this our leave it and I'm happy with this feature =)

**Comment by evert** [comment]
If you like the `--outDir` and `--outFile` ideas to have familiarity with typescript, happy to do the implementation too!

**Comment by coreyarms** [comment]
I like the `outDir` and `outFile` approach. I implemented it in the main function, would you be able to update the cli? [I opened a PR](https://github.com/coreyarms/mysql-types-generator/pull/8) for the `outputOptions` branch, I guess you can add your commits to it?

Check line 76 in `cli.ts`, I just wrote it to make the build/test work temporarily.
